// ==============================================================
// Phase 4 acceptance — identity, commercial contract, operations (PH4-01..33)
// ==============================================================
import { beforeAll, afterAll, describe, expect, it } from 'vitest';
import crypto from 'crypto';
import { runMigrations } from '../src/infrastructure/database/migrations';
import { seedDatabase } from '../src/infrastructure/database/seed';
import { getDatabaseClient, resetDatabaseClientForTesting } from '../src/infrastructure/database/db-client';
import { AccountLinkingService } from '../src/application/services/account-linking-service';
import { resolveTelegramTenantContext, requireChannelAccess, TenantAccessError } from '../src/application/services/tenant-context-service';
import { EntitlementGuard, EntitlementService, UsageMeter, IntegrationOutboxService } from '../src/application/services/entitlement-service';
import { SubscriptionService } from '../src/application/services/subscription-service';
import { SubscriptionStatus } from '../src/domain/types';
import { verifyIntegrationWebhook, WebhookVerificationError } from '../src/infrastructure/security/integration-webhook-verifier';
import { EditorialPlanningService } from '../src/application/services/editorial-planning-service';
import { BackgroundJobOrchestrator } from '../src/infrastructure/background/job-orchestrator';

const product = 'ai-channel-manager';
const features = { autonomousGeneration: true, webResearch: true, socialResearch: false, strategyRecommendations: true, advancedEditorialPlanning: true };
const limits = { maxChannels: 2, postsPerDay: 3, aiRequestsPerDay: 4, researchRunsPerDay: 3, generationIntervalSeconds: 0, researchIntervalSeconds: 60 };
let db: ReturnType<typeof getDatabaseClient>;
let accountA = ''; let workspaceA = ''; let workspaceB = '';

async function entitlement(accountId: string, status: SubscriptionStatus = SubscriptionStatus.ACTIVE, version = 1) {
  await db.query(`INSERT INTO entitlement_snapshots (id,account_id,product_key,status,plan_code,valid_until,features_json,limits_json,version,source,is_active) VALUES ($1,$2,$3,$4,'test',CURRENT_TIMESTAMP + INTERVAL '1 day',$5,$6,$7,'MOCK',TRUE)`, [`ent-${accountId}-${version}`, accountId, product, status, JSON.stringify(features), JSON.stringify(limits), version]);
  EntitlementService.clearCacheForTesting();
}

describe('Phase 4 Acceptance Tests', () => {
  beforeAll(async () => {
    process.env.DEMO_MODE = 'true'; process.env.PLATFORM_MIN_GENERATION_INTERVAL_SECONDS = '300';
    await runMigrations(); await seedDatabase(true); db = getDatabaseClient();
    const accounts = new AccountLinkingService();
    accountA = await accounts.createAccount({ externalProvider: 'test', externalUserId: 'alice', displayName: 'Alice' });
    workspaceA = await accounts.createWorkspace(accountA, { name: 'Alice Workspace', slug: `alice-${Date.now()}` });
    const accountB = await accounts.createAccount({ externalProvider: 'test', externalUserId: 'bob', displayName: 'Bob' });
    workspaceB = await accounts.createWorkspace(accountB, { name: 'Bob Workspace', slug: `bob-${Date.now()}` });
    await db.query(`INSERT INTO products (product_key,name,status) VALUES ($1,'AI Channel Manager','ACTIVE') ON CONFLICT (product_key) DO NOTHING`, [product]);
    await entitlement(accountA);
  });
  afterAll(async () => { await resetDatabaseClientForTesting(); });

  it('PH4-01 account creation resolves one external identity', async () => { expect(accountA).toMatch(/^acc-/); expect((await db.query('SELECT * FROM accounts WHERE id=$1',[accountA])).rowCount).toBe(1); });
  it('PH4-02 workspace membership supports multiple workspaces', async () => { expect((await db.query('SELECT * FROM workspace_members WHERE workspace_id IN ($1,$2)',[workspaceA,workspaceB])).rowCount).toBe(2); });
  it('PH4-03 account-link token is opaque and token secret is not persisted', async () => { const challenge=await new AccountLinkingService().createLinkChallenge(accountA,workspaceA); const raw=await db.query('SELECT token_hash FROM account_link_tokens WHERE account_id=$1 ORDER BY created_at DESC LIMIT 1',[accountA]); expect(raw.rows[0].token_hash).not.toBe(challenge.token); });
  it('PH4-04 Telegram link consumes a valid token once', async () => { const c=await new AccountLinkingService().createLinkChallenge(accountA,workspaceA); const linked=await new AccountLinkingService().consumeLinkChallenge({token:c.token,telegramUserId:'444001',username:'alice'}); expect(linked.accountId).toBe(accountA); });
  it('PH4-05 replayed link token is rejected', async () => { const c=await new AccountLinkingService().createLinkChallenge(accountA,workspaceA); await new AccountLinkingService().consumeLinkChallenge({token:c.token,telegramUserId:'444002'}); await expect(new AccountLinkingService().consumeLinkChallenge({token:c.token,telegramUserId:'444002'})).rejects.toThrow(/invalid|expired|consumed/i); });
  it('PH4-06 expired link token is rejected and attempt is recorded', async () => { const c=await new AccountLinkingService().createLinkChallenge(accountA,workspaceA); await db.query("UPDATE account_link_tokens SET expires_at=CURRENT_TIMESTAMP - INTERVAL '1 second' WHERE token_hash=$1",[crypto.createHash('sha256').update(c.token).digest('hex')]); await expect(new AccountLinkingService().consumeLinkChallenge({token:c.token,telegramUserId:'444003'})).rejects.toThrow(); expect((await db.query("SELECT * FROM account_link_attempts WHERE telegram_user_id='444003'")).rowCount).toBe(1); });
  it('PH4-07 Telegram identity cannot be silently reassigned', async () => { const service=new AccountLinkingService(); const other=await service.createAccount({externalProvider:'test',externalUserId:'mallory'}); const ws=await service.createWorkspace(other,{name:'Other',slug:`other-${Date.now()}`}); const c=await service.createLinkChallenge(other,ws); await expect(service.consumeLinkChallenge({token:c.token,telegramUserId:'444001'})).rejects.toThrow(/already linked/i); });
  it('PH4-08 Telegram context resolves account and workspace', async () => { const ctx=await resolveTelegramTenantContext('444001'); expect(ctx?.accountId).toBe(accountA); expect(ctx?.workspaceId).toBe(workspaceA); });
  it('PH4-09 cross-workspace channel access is rejected', async () => { await db.query(`INSERT INTO channels (id,workspace_id,name,language,status) VALUES ('ch-ph4-a',$1,'A','en','ACTIVE') ON CONFLICT (id) DO NOTHING`,[workspaceA]); const ctx={accountId:accountA,workspaceId:workspaceB,role:'OWNER' as const,isDemo:false}; await expect(requireChannelAccess(ctx,'ch-ph4-a')).rejects.toBeInstanceOf(TenantAccessError); });
  it('PH4-10 ACTIVE entitlement resolves from versioned snapshot', async () => { const e=await new EntitlementService().resolve(accountA); expect(e?.status).toBe(SubscriptionStatus.ACTIVE); expect(e?.limits.maxChannels).toBe(2); });
  it('PH4-11 platform generation safety floor applies when plan returns zero', async () => { const guard=new EntitlementGuard(); await guard.assertGenerationInterval({accountId:accountA,workspaceId:workspaceA,channelId:'ch-ph4-a'}); await guard.markGenerated('ch-ph4-a'); await expect(guard.assertGenerationInterval({accountId:accountA,workspaceId:workspaceA,channelId:'ch-ph4-a'})).rejects.toThrow(/interval/i); });
  it('PH4-12 usage insertion is idempotent', async () => { const meter=new UsageMeter(); expect(await meter.record({accountId:accountA,workspaceId:workspaceA,productKey:product,metric:'AI_REQUEST',source:'test',idempotencyKey:'ph4-usage-1'})).toBe(true); expect(await meter.record({accountId:accountA,workspaceId:workspaceA,productKey:product,metric:'AI_REQUEST',source:'test',idempotencyKey:'ph4-usage-1'})).toBe(false); });
  it('PH4-13 daily usage counters accumulate immutable events', async () => { const meter=new UsageMeter(); await meter.record({accountId:accountA,workspaceId:workspaceA,productKey:product,metric:'RESEARCH_RUN',source:'test',idempotencyKey:'ph4-usage-2'}); expect(await meter.usageToday({accountId:accountA,workspaceId:workspaceA,productKey:product,metric:'RESEARCH_RUN'})).toBeGreaterThan(0); });
  it('PH4-14 atomic reservation rejects quota overrun', async () => { const meter=new UsageMeter(); expect(await meter.reserve({accountId:accountA,workspaceId:workspaceA,productKey:product,metric:'POST_PUBLISHED',maximum:1,source:'test',idempotencyKey:'ph4-res-1'})).toBe(true); expect(await meter.reserve({accountId:accountA,workspaceId:workspaceA,productKey:product,metric:'POST_PUBLISHED',maximum:1,source:'test',idempotencyKey:'ph4-res-2'})).toBe(false); });
  it('PH4-15 usage recording creates an idempotent outbox event', async () => { expect((await db.query("SELECT * FROM integration_outbox WHERE event_type='usage.recorded'")).rowCount).toBeGreaterThan(0); });
  it('PH4-16 outbox pending event can be claimed', async () => { const claimed=await new IntegrationOutboxService().claimPending(5); expect(Array.isArray(claimed)).toBe(true); });
  it('PH4-17 outbox completion state is durable', async () => { const row=await db.query("SELECT id FROM integration_outbox WHERE status='PROCESSING' LIMIT 1"); if(row.rowCount){await new IntegrationOutboxService().markDelivered(row.rows[0].id); expect((await db.query("SELECT status FROM integration_outbox WHERE id=$1",[row.rows[0].id])).rows[0].status).toBe('COMPLETED');} });
  it('PH4-18 valid HMAC webhook signature verifies', () => { const raw='{"eventType":"subscription.activated"}', ts=String(Math.floor(Date.now()/1000)), secret='ph4-secret'; const sig=crypto.createHmac('sha256',secret).update(`${ts}.${raw}`).digest('hex'); expect(verifyIntegrationWebhook({rawBody:raw,timestamp:ts,signature:sig,eventId:'ph4-hook-1',secret}).eventId).toBe('ph4-hook-1'); });
  it('PH4-19 invalid HMAC webhook signature rejects', () => { expect(()=>verifyIntegrationWebhook({rawBody:'{}',timestamp:String(Math.floor(Date.now()/1000)),signature:'00',eventId:'ph4-hook-bad',secret:'x'})).toThrow(WebhookVerificationError); });
  it('PH4-20 stale webhook timestamp rejects', () => { const raw='{}',ts=String(Math.floor(Date.now()/1000)-1000),secret='x',sig=crypto.createHmac('sha256',secret).update(`${ts}.${raw}`).digest('hex'); expect(()=>verifyIntegrationWebhook({rawBody:raw,timestamp:ts,signature:sig,eventId:'stale',secret})).toThrow(/timestamp/i); });
  it('PH4-21 subscription event applies an ACTIVE snapshot', async () => { const service=new SubscriptionService(); await service.apply({eventId:'ph4-sub-1',accountId:accountA,productKey:product,planCode:'test',status:SubscriptionStatus.ACTIVE,eventType:'subscription.activated',features,limits}); expect((await db.query('SELECT * FROM subscriptions WHERE account_id=$1 AND product_key=$2',[accountA,product])).rowCount).toBe(1); });
  it('PH4-22 repeated subscription event is idempotent', async () => { const service=new SubscriptionService(); await service.apply({eventId:'ph4-sub-1',accountId:accountA,productKey:product,planCode:'test',status:SubscriptionStatus.ACTIVE,eventType:'subscription.activated',features,limits}); expect(Number((await db.query("SELECT count(*) AS count FROM integration_webhook_events WHERE event_id='ph4-sub-1'")).rows[0].count)).toBe(1); });
  it('PH4-23 suspended entitlement denies premium operations', async () => { await db.query('UPDATE entitlement_snapshots SET is_active=FALSE WHERE account_id=$1 AND product_key=$2',[accountA,product]); await entitlement(accountA,SubscriptionStatus.SUSPENDED,9); await expect(new EntitlementGuard().getActive(accountA)).rejects.toThrow(/not entitled/i); await db.query('UPDATE entitlement_snapshots SET is_active=FALSE WHERE account_id=$1 AND product_key=$2',[accountA,product]); await entitlement(accountA,SubscriptionStatus.ACTIVE,10); });
  it('PH4-24 daily plan uses channel Brain and stored candidates only', async () => { const result=await new EditorialPlanningService().buildDailyPlan({accountId:'acc-demo-001',workspaceId:'ws-demo-001',channelId:'ch-futurestack-001',force:true}); expect(result.channelId).toBe('ch-futurestack-001'); expect(result.rationale?.performanceData).toContain('unavailable'); });
  it('PH4-25 explicit preferences remain present in planning rationale', async () => { const plan=await new EditorialPlanningService().buildDailyPlan({accountId:'acc-demo-001',workspaceId:'ws-demo-001',channelId:'ch-futurestack-001'}); expect((plan.rationale?.explicitOwnerRules as string[]).length).toBeGreaterThan(0); });
  it('PH4-26 owner learning events persist edits', async () => { const planner=new EditorialPlanningService(); await planner.recordLearning({workspaceId:'ws-demo-001',channelId:'ch-futurestack-001',action:'EDIT',signalKey:'length',signalValue:'shorter'}); expect((await db.query("SELECT * FROM editorial_learning_events WHERE signal_key='length'")).rowCount).toBe(1); });
  it('PH4-27 owner learning events persist rejects', async () => { const planner=new EditorialPlanningService(); await planner.recordLearning({workspaceId:'ws-demo-001',channelId:'ch-futurestack-001',action:'REJECT',signalKey:'topic',signalValue:'hype'}); expect((await db.query("SELECT * FROM editorial_learning_events WHERE action='REJECT'")).rowCount).toBeGreaterThan(0); });
  it('PH4-28 strategy recommendations remain pending owner approval', async () => { const id=await new EditorialPlanningService().createStrategyRecommendation({workspaceId:'ws-demo-001',channelId:'ch-futurestack-001'}); if(id) expect((await db.query('SELECT status FROM strategy_recommendations WHERE id=$1',[id])).rows[0].status).toBe('PENDING'); });
  it('PH4-29 performance absence is represented, never fabricated', async () => { expect(Number((await db.query(`SELECT count(*) AS count FROM channel_performance_daily WHERE available=TRUE`)).rows[0].count)).toBe(0); });
  it('PH4-30 worker sees all active channels rather than selecting one global channel', async () => { const worker=new BackgroundJobOrchestrator(); const result=await worker.runAutonomousCycle(2); expect(result.channelsConsidered).toBeGreaterThanOrEqual(2); });
  it('PH4-31 upgrade applies a new plan snapshot immediately', async () => { const service=new SubscriptionService(); await service.apply({eventId:'ph4-upgrade-1',accountId:accountA,productKey:product,planCode:'pro',status:SubscriptionStatus.ACTIVE,eventType:'subscription.upgraded',features,limits:{...limits,maxChannels:10}}); const active=await db.query(`SELECT plan_code,limits_json FROM entitlement_snapshots WHERE account_id=$1 AND product_key=$2 AND is_active=TRUE`,[accountA,product]); expect(active.rows[0].plan_code).toBe('pro'); expect(JSON.parse(active.rows[0].limits_json).maxChannels).toBe(10); });
  it('PH4-32 future downgrade is retained until effectiveAt', async () => { const service=new SubscriptionService(); const effectiveAt=new Date(Date.now()+3600_000).toISOString(); await service.apply({eventId:'ph4-downgrade-1',accountId:accountA,productKey:product,planCode:'basic',status:SubscriptionStatus.ACTIVE,eventType:'subscription.downgraded',effectiveAt,features,limits}); const subscription=await db.query(`SELECT plan_code,pending_plan_code,effective_at FROM subscriptions WHERE account_id=$1 AND product_key=$2`,[accountA,product]); expect(subscription.rows[0].plan_code).toBe('pro'); expect(subscription.rows[0].pending_plan_code).toBe('basic'); });
  it('PH4-33 worker-side downgrade applies at its effective boundary', async () => { await db.query(`INSERT INTO plans(product_key,plan_code,name,feature_defaults,limit_defaults,status) VALUES($1,'basic','Basic',$2,$3,'ACTIVE') ON CONFLICT(product_key,plan_code) DO UPDATE SET feature_defaults=EXCLUDED.feature_defaults,limit_defaults=EXCLUDED.limit_defaults`,[product,JSON.stringify(features),JSON.stringify(limits)]); await db.query(`UPDATE subscriptions SET effective_at=CURRENT_TIMESTAMP - INTERVAL '1 second' WHERE account_id=$1 AND product_key=$2`,[accountA,product]); expect(await new SubscriptionService().applyDueDowngrades()).toBeGreaterThan(0); const subscription=await db.query(`SELECT plan_code,pending_plan_code FROM subscriptions WHERE account_id=$1 AND product_key=$2`,[accountA,product]); expect(subscription.rows[0].plan_code).toBe('basic'); expect(subscription.rows[0].pending_plan_code).toBeNull(); });
});
