'use client';

import React, { useState, useEffect } from 'react';
import { Palette, Sparkles, CheckCircle2, ShieldCheck, RefreshCw } from 'lucide-react';

export default function BrandPage() {
  const [proposals, setProposals] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [notification, setNotification] = useState<string | null>(null);

  const fetchProposals = () => {
    fetch('/api/brand/proposals')
      .then((res) => res.json())
      .then((data) => setProposals(data || []))
      .catch(console.error);
  };

  useEffect(() => {
    fetchProposals();
  }, []);

  const generateProposal = async () => {
    setGenerating(true);
    try {
      const res = await fetch('/api/brand/propose', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ channelId: 'ch-futurestack-001' }),
      });
      const data = await res.json();
      setNotification('New brand proposal generated by AI! Awaiting owner review.');
      fetchProposals();
    } finally {
      setGenerating(false);
      setTimeout(() => setNotification(null), 4000);
    }
  };

  const applyProposal = async (proposalId: string) => {
    try {
      await fetch('/api/brand/apply', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ proposalId, ownerUserId: '987654321' }),
      });
      setNotification('Branding proposal applied to channel metadata!');
      fetchProposals();
    } finally {
      setTimeout(() => setNotification(null), 4000);
    }
  };

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center">
            <Palette className="w-6 h-6 mr-2 text-blue-400" />
            Channel Brand Manager
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            AI-proposed visual identity, channel bio, description, and positioning (YELLOW permission level: owner approval strictly required).
          </p>
        </div>

        <button
          onClick={generateProposal}
          disabled={generating}
          className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg text-xs font-medium flex items-center space-x-1.5 transition-colors disabled:opacity-50"
        >
          {generating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
          <span>{generating ? 'Designing...' : 'Generate New Brand Proposal'}</span>
        </button>
      </div>

      {notification && (
        <div className="bg-blue-950/80 border border-blue-500/40 text-blue-300 text-xs px-4 py-3 rounded-lg flex items-center">
          <CheckCircle2 className="w-4 h-4 mr-2 text-emerald-400" />
          <span>{notification}</span>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {proposals.map((p) => (
          <div key={p.id} className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4 shadow-sm">
            <div className="flex items-start justify-between">
              <div>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-blue-900/60 text-blue-300">
                  BRAND PROPOSAL
                </span>
                <h3 className="font-bold text-base text-white mt-1.5">{p.proposed_name}</h3>
              </div>
              <span className={`px-2 py-0.5 text-xs rounded-full font-medium ${p.status === 'APPLIED' ? 'bg-emerald-950 text-emerald-300 border border-emerald-500/30' : 'bg-amber-950 text-amber-300 border border-amber-500/30'}`}>
                {p.status}
              </span>
            </div>

            <div>
              <span className="text-slate-400 text-xs font-medium block mb-1">Positioning Statement:</span>
              <p className="text-xs text-slate-300 bg-slate-950 p-3 rounded-lg border border-slate-800 leading-relaxed">
                {p.positioning}
              </p>
            </div>

            <div>
              <span className="text-slate-400 text-xs font-medium block mb-1">Channel Description:</span>
              <p className="text-xs text-slate-300 bg-slate-950 p-3 rounded-lg border border-slate-800 leading-relaxed">
                {p.proposed_description}
              </p>
            </div>

            <div className="pt-2 border-t border-slate-800 flex items-center justify-between">
              <span className="text-[11px] text-slate-500">
                Created: {new Date(p.created_at).toLocaleDateString()}
              </span>

              {p.status === 'PENDING' && (
                <button
                  onClick={() => applyProposal(p.id)}
                  className="px-3.5 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-medium flex items-center space-x-1"
                >
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>Approve & Apply to Channel</span>
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
